# Generated by Django 4.0.1 on 2022-01-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
    ]
