# Generated by Django 4.0.1 on 2022-01-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_user_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='doc_ide',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
